### ISSUE TITLE
0.22.1 update breaks the console output on build 

### ISSUE THREAD

**Issue by juannerito** [elm-community/SublimeElmLanguageSupport#48]
When Sublime Text updated the Package to 0.22.1, it broke the build output for me. 

I'm getting this output in the console: 

```reloading plugin Elm Language Support.elm_make
Running elm-make /Users/john/go/src/github.com/XXXXX/XXXXXX//src/elm/src/Animations.elm --output=/dev/null --report=json --yes
Running elm-make /Users/john/go/src/github.com/XXXXX/XXXXXX//src/elm/src/Main.elm --output=/dev/null --report=json --yes

reloading plugin Elm Language Support.elm_make
Running elm-make /Users/john/go/src/github.com/XXXXX/XXXXXX/src/elm/src/Main.elm --output=/dev/null --report=json --yes
Exception in thread Thread-16:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "exec in /Applications/Sublime Text.app/Contents/MacOS/Packages/Default.sublime-package", line 139, in read_stdout
  File "/Users/john/Library/Application Support/Sublime Text 3/Packages/Elm Language Support/elm_make.py", line 53, in on_data
    self.buffer += data
TypeError: Can't convert 'bytes' object to str implicitly
```

Reverting to 0.22.0, the build tool works as expected. 

FWIW, I'm running on Mac OS 10.13.3

Thanks for such a great package, btw.

**Comment by ianmackenzie** [comment]
Same error for me - I'm on Windows 10.

**Comment by branjwong** [comment]
Same for me -- Fedora 25

**Comment by sentience** [comment]
@juannerito, @ianmackenzie, @branjwong can you confirm which release of Sublime Text 3 you are running?

It appears that there were some changes made to build systems in Sublime Text 3 r3153 to fix SublimeTextIssues/Core#1951, which broke this package on some systems (#44). The fix for that, which was released in 0.22.1, in turn may have broken compatibility with previous versions of Sublime Text 3.

If I can confirm that the three of you are using a version older than r3153, that will confirm my theory. I think I’ll be able to write a fix that is compatible with both the old and new versions.

**Comment by sentience** [comment]
I’ve just released 0.22.2 with an attempted fix for this issue.

**Comment by ianmackenzie** [comment]
Ah, good catch @sentience, I'm currently on build 3143 (latest stable). With 0.22.2, I do get the `[Finished in 1.1s]` text displayed (where with 0.22.1 there was no output at all), but I still don't get any error messages for failed builds - it just finishes quicker =)

**Comment by juannerito** [comment]
@sentience I'm on version 3143 as well. I can confirm that with 0.22.2 I'm getting the same output as @ianmackenzie. I'm also getting an Exit Code 1 on files that I know I have compilation issues ex `[Finished in 1.0s with exit code 1]`, so it appears to be working minus the feedback from the compiler.

**Comment by sentience** [comment]
Ok I'll continue to investigate!

**Comment by branjwong** [comment]
I'm on Build 3143!

**Comment by sentience** [comment]
OK, build output should now be working properly again in all ST3 releases with the release of 0.22.3.
